global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@localhost'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'

  # Uncomment and configure for email alerts
  # - name: 'email'
  #   email_configs:
  #     - to: 'admin@localhost'
  #       subject: 'Alert: {{ .GroupLabels.alertname }}'
  #       body: |
  #         {{ range .Alerts }}
  #         Alert: {{ .Annotations.summary }}
  #         Description: {{ .Annotations.description }}
  #         {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
