apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      httpMethod: POST

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: POST
